### ISSUE TITLE
BlacklistedClasses

### ISSUE THREAD

**Issue by clergyman48** [MineSworn/UltimateArena#92]
Hi,

BlacklistedClasses option does not work.
I use  UltimateArena v2.7 on Spigot-1493
My config of infected arena look like this:

gameTime: 120
lobbyTime: 60
maxDeaths: 2
allowTeamKilling: false
countMobKills: false
rewardBasedOnXp: false
cashReward: 100
BlacklistedClasses: Gunner
whitelistedClasses: Test
rewards:

But I can't install another class for default, on this type of game.  Only Gunner

**Comment by dmulloy2** [comment]
The casing is wrong, it should be
````yaml
blacklistedClasses:
  - gunner
whitelistedClasses:
  - test
````
